<?php

declare(strict_types=1);

namespace ReportedIp\Honeypot\Tests\Integration;

use ReportedIp\Honeypot\Tests\TestCase;

/**
 * Integration tests for full end-to-end request processing.
 *
 * These tests verify the complete request lifecycle:
 * - Request arrives at the entry point
 * - IP resolution from proxy headers
 * - Detection pipeline processes all analyzers
 * - Results are logged to the database
 * - Response is generated by the appropriate trap
 * - Report is queued for the API
 *
 * Requirements:
 * - Docker environment running (php-fpm + nginx)
 * - SQLite writable at the configured path
 * - Network access for curl-based HTTP requests
 *
 * To run: php tests/run-tests.php --integration
 */
final class FullRequestTest extends TestCase
{
    public function testSqlInjectionRequestEndToEnd(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testBruteForceRequestEndToEnd(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testCleanRequestReturnsHoneypotPage(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testXmlRpcAttackIsLoggedAndReported(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testMultipleAnalyzersFireOnComplexAttack(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testWhitelistedIpIsNotReported(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }

    public function testRateLimitPreventsLogFlooding(): void
    {
        $this->t->skip('Integration test: requires Docker environment');
    }
}
