<?php

declare(strict_types=1);

namespace ReportedIp\Honeypot\Detection;

use ReportedIp\Honeypot\Persistence\Database;

/**
 * Canary / tripwire credential service.
 *
 * When an attacker grabs a fake config file (.env, wp-config.php.bak, .git,
 * phpMyAdmin export, ...) the trap embeds a set of unique fake credentials
 * generated by this service and persists them. Every subsequent request is
 * scanned for those exact values: reuse of a leaked credential — no matter
 * from which IP — is a confirmed-malicious signal with zero false positives,
 * because the value only ever existed inside a hidden honeypot response.
 *
 * All honeytokens carry the shared marker prefix {@see self::MARKER} so they
 * can be located inside an arbitrary request with a single cheap regex before
 * any database lookup happens.
 */
final class Honeytoken
{
    /**
     * Shared marker embedded in every honeytoken value. Chosen to look like a
     * plausible random substring while being unique enough to never collide
     * with legitimate traffic.
     */
    public const MARKER = 'HPt';

    /** Regex that extracts candidate honeytoken values from a request string. */
    private const EXTRACT_REGEX = '/HPt[0-9a-f]{16}/';

    public function __construct(private readonly Database $db) {}

    /**
     * Get (or lazily create) the honeytoken of a given type for an IP.
     *
     * Deterministic per (ip, type): repeated grabs of the same config file
     * return the same value instead of flooding the table.
     *
     * @param string $type       Logical slot, e.g. 'db_password', 'aws_secret', 'api_key'.
     * @param string $ip         The IP the token is being leaked to.
     * @param string $sourcePath The path that leaked it (for later correlation).
     */
    public function issue(string $type, string $ip, string $sourcePath): string
    {
        try {
            $existing = $this->db->query(
                'SELECT token FROM honeypot_honeytokens WHERE issued_to_ip = ? AND token_type = ? LIMIT 1',
                [$ip, $type]
            )->fetchColumn();

            if (is_string($existing) && $existing !== '') {
                return $existing;
            }

            $token = self::MARKER . bin2hex(random_bytes(8));
            $this->db->insert('honeypot_honeytokens', [
                'token'        => $token,
                'token_type'   => $type,
                'issued_to_ip' => $ip,
                'source_path'  => substr($sourcePath, 0, 255),
            ]);

            return $token;
        } catch (\Throwable $e) {
            // Never let honeytoken bookkeeping break a trap response.
            return self::MARKER . bin2hex(random_bytes(8));
        }
    }

    /**
     * Scan a request for reuse of any previously issued honeytoken.
     *
     * Searches URI, body, POST values, cookies and the Authorization header.
     * On a hit the token is marked triggered and a DetectionResult is returned.
     */
    public function detectReuse(
        string $haystack,
        string $reuseIp
    ): ?DetectionResult {
        if (!str_contains($haystack, self::MARKER)) {
            return null;
        }

        if (!preg_match_all(self::EXTRACT_REGEX, $haystack, $matches)) {
            return null;
        }

        $candidates = array_unique($matches[0]);

        foreach ($candidates as $candidate) {
            try {
                $row = $this->db->query(
                    'SELECT id, token_type, issued_to_ip, source_path FROM honeypot_honeytokens WHERE token = ? LIMIT 1',
                    [$candidate]
                )->fetch();
            } catch (\Throwable $e) {
                continue;
            }

            if ($row === false || $row === null) {
                continue;
            }

            $this->markTriggered((int) $row['id'], $reuseIp);

            $sameIp = ($row['issued_to_ip'] === $reuseIp);
            $comment = sprintf(
                'Honeytoken reuse: leaked %s credential from %s replayed%s',
                $row['token_type'],
                $row['source_path'] !== '' ? $row['source_path'] : 'a fake config',
                $sameIp ? ' by the same IP' : sprintf(' (leaked to %s)', $row['issued_to_ip'])
            );

            // Confirmed malicious: hacking + brute-force + backdoor + honeytoken.
            return new DetectionResult([15, 18, 28, 59], $comment, 100, 'Honeytoken');
        }

        return null;
    }

    /**
     * Mark a honeytoken as triggered and bump its counter.
     */
    private function markTriggered(int $id, string $reuseIp): void
    {
        try {
            $this->db->query(
                'UPDATE honeypot_honeytokens
                 SET triggered = 1,
                     triggered_by_ip = ?,
                     triggered_at = CURRENT_TIMESTAMP,
                     trigger_count = trigger_count + 1
                 WHERE id = ?',
                [$reuseIp, $id]
            );
        } catch (\Throwable $e) {
            // Best-effort bookkeeping.
        }
    }
}
